name: Deploy Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sshpass and rsync
      run: sudo apt-get install -y sshpass rsync

    - name: Deploy to EC2
      run: |
        # Create target directory if not exists
        sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.EC2_TARGET_DIR }}"

        # Sync website files (only index.html in this example)
        sshpass -p "${{ secrets.EC2_PASSWORD }}" rsync -avz --delete \
        -e "ssh -o StrictHostKeyChecking=no" \
        index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_TARGET_DIR }}

        # Restart Apache on EC2
        sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart apache2"
