name: Copy Files to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      TARGET_PATH: "/var/www/html/"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass and rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync

      - name: Copy Files using rsync
        run: |
          rsync -avz --delete \
            -e "sshpass -p \"$SERVER_PASSWORD\" ssh -o StrictHostKeyChecking=no" \
            index.html "$SERVER_USER@$SERVER_IP:$TARGET_PATH"

      - name: Restart apache2 on Server
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "sudo systemctl restart apache2"
